# Generated by Django 6.0.4 on 2026-04-30 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField()),
                ('site_id', models.IntegerField()),
                ('schedule_type', models.CharField(max_length=255)),
                ('mailing_list_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('sent', models.BigIntegerField()),
                ('opened', models.BigIntegerField()),
                ('clicked', models.BigIntegerField()),
                ('subscribed', models.BigIntegerField()),
                ('unsubscribed', models.BigIntegerField()),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingestion.campaign')),
            ],
        ),
    ]
