#!/bin/sh
set -e

# Se hai ENV di default (opzionali)
HOST=${HOST:-0.0.0.0}
PORT=${PORT:-8000}
WORKER_THREADS=${WORKER_THREADS:-4}
RELOAD=""

if [ $DEBUG ]; then
  RELOAD="--reload"
fi

if [ -f "manage.py" ] && [ -x "manage.py" ]; then
    ./manage.py migrate
fi


# Avvia gunicorn passando i parametri
exec gunicorn --bind "$HOST":"$PORT" --threads "$WORKER_THREADS" $RELOAD "$@"