name: "Test Image"
run-name: Test by @${{ github.actor }}
on: ["push", "pull_request"]
jobs: 
  py_test: 
    name: 'python UnitTest'
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v6 
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: requirements.txt
      - name: Install Dependencies
        run: |
          pip install --upgrade pip 
          pip install -r requirements.txt 
      - name: Testing
        env:
          API_ENDPOINT: ${{ vars.API_ENDPOINT }}
          SITE_ID: ${{ vars.SITE_ID }}
          API_KEY: ${{ secrets.API_KEY }}
        run: python -m unittest discover -s tests -p "test_*.py"